import type { TrafficViolation } from '@/types';

export const mockViolations: TrafficViolation[] = [
  {
    id: '1',
    violationCode: 'VL001',
    violationNumber: 'BB2024001',
    violatorInfo: {
      name: 'Nguyễn Văn An',
      licenseNumber: '012345678901',
      idNumber: '001234567890',
      dateOfBirth: '1990-05-15',
      address: '123 Đường Láng, Đống Đa, Hà Nội',
      phone: '0912345678',
      email: 'nguyenvanan@email.com',
    },
    vehicleInfo: {
      plateNumber: '29A-12345',
      type: 'Ô tô con',
      brand: 'Toyota',
      model: 'Camry',
      color: 'Trắng',
      owner: 'Nguyễn Văn An',
    },
    violationType: 'speed_limit_20_35',
    violationDate: '2024-11-15',
    violationTime: '14:30:00',
    location: {
      address: 'Đường Láng - Đại La',
      province: 'Hà Nội',
      district: 'Đống Đa',
      street: 'Láng',
      landmark: 'Gần BigC',
    },
    officer: {
      id: 'OFF001',
      name: 'Trần Văn B',
      badgeNumber: 'CSGT001',
      unit: 'Phòng CSGT Hà Nội',
      rank: 'Trung úy',
    },
    description: 'Vượt quá tốc độ cho phép 25 km/h trên đường Láng',
    fine: 2000000,
    pointsDeducted: 2,
    status: 'unpaid',
    evidence: [
      {
        id: 'EV001',
        type: 'camera',
        description: 'Camera giao thông ghi nhận tốc độ 85 km/h (giới hạn 60 km/h)',
        captureDate: '2024-11-15T14:30:00Z',
        verified: true,
      },
      {
        id: 'EV002',
        type: 'photo',
        description: 'Ảnh chụp biển số xe',
        captureDate: '2024-11-15T14:30:00Z',
        verified: true,
      },
    ],
    createdAt: '2024-11-15T15:00:00Z',
  },
  {
    id: '2',
    violationCode: 'VL002',
    violationNumber: 'BB2024002',
    violatorInfo: {
      name: 'Lê Văn Cường',
      licenseNumber: '012345678903',
      idNumber: '001234567892',
      dateOfBirth: '1992-12-03',
      address: '789 Giải Phóng, Hai Bà Trưng, Hà Nội',
      phone: '0909123456',
    },
    vehicleInfo: {
      plateNumber: '29C-11111',
      type: 'Xe tải',
      brand: 'Hino',
      model: '300 Series',
      color: 'Xanh',
      owner: 'Lê Văn Cường',
    },
    violationType: 'alcohol_level_2',
    violationDate: '2024-11-20',
    violationTime: '22:15:00',
    location: {
      address: 'Đường Giải Phóng',
      province: 'Hà Nội',
      district: 'Hai Bà Trưng',
      street: 'Giải Phóng',
      landmark: 'Ngã tư Giải Phóng - Trường Chinh',
    },
    officer: {
      id: 'OFF002',
      name: 'Phạm Thị C',
      badgeNumber: 'CSGT002',
      unit: 'Đội CSGT số 6',
      rank: 'Đại úy',
    },
    description: 'Điều khiển xe khi đã sử dụng rượu bia, nồng độ cồn 0.35mg/lít khí thở',
    fine: 8000000,
    pointsDeducted: 4,
    status: 'paid',
    paymentInfo: {
      paymentId: 'PAY001',
      paymentMethod: 'bank_transfer',
      amount: 8000000,
      paymentDate: '2024-11-22',
      transactionNumber: 'TXN123456',
      receiptNumber: 'RCP001',
      status: 'completed',
    },
    evidence: [
      {
        id: 'EV003',
        type: 'breathalyzer',
        description: 'Kết quả đo nồng độ cồn: 0.35mg/lít khí thở',
        captureDate: '2024-11-20T22:15:00Z',
        verified: true,
      },
      {
        id: 'EV004',
        type: 'video',
        description: 'Video ghi hình quá trình kiểm tra',
        captureDate: '2024-11-20T22:15:00Z',
        verified: true,
      },
    ],
    createdAt: '2024-11-20T22:30:00Z',
  },
  {
    id: '3',
    violationCode: 'VL003',
    violationNumber: 'BB2024003',
    violatorInfo: {
      name: 'Phạm Thị Dung',
      licenseNumber: '012345678904',
      idNumber: '001234567893',
      dateOfBirth: '1988-02-28',
      address: '321 Láng Hạ, Ba Đình, Hà Nội',
      phone: '0976543210',
    },
    vehicleInfo: {
      plateNumber: '29B-22222',
      type: 'Xe máy',
      brand: 'Honda',
      model: 'Wave RSX',
      color: 'Đỏ',
      owner: 'Phạm Thị Dung',
    },
    violationType: 'red_light',
    violationDate: '2024-11-18',
    violationTime: '08:45:00',
    location: {
      address: 'Ngã tư Láng Hạ - Thái Hà',
      province: 'Hà Nội',
      district: 'Đống Đa',
      street: 'Láng Hạ',
      coordinates: {
        latitude: 21.0145,
        longitude: 105.8125,
      },
    },
    officer: {
      id: 'OFF003',
      name: 'Hoàng Văn D',
      badgeNumber: 'CSGT003',
      unit: 'Đội CSGT số 2',
      rank: 'Thiếu úy',
    },
    description: 'Vượt đèn đỏ tại ngã tư Láng Hạ - Thái Hà',
    fine: 5000000,
    pointsDeducted: 3,
    status: 'appealed',
    appeal: {
      id: 'APP001',
      violationId: '3',
      appellant: 'Phạm Thị Dung',
      appealDate: '2024-11-19',
      reason: 'Đèn tín hiệu bị hỏng, nhấp nháy liên tục',
      evidence: [
        {
          id: 'EV005',
          type: 'photo',
          description: 'Ảnh chụp đèn tín hiệu bị hỏng',
          captureDate: '2024-11-18T08:45:00Z',
          verified: false,
        },
      ],
      status: 'under_review',
    },
    evidence: [
      {
        id: 'EV006',
        type: 'camera',
        description: 'Camera giao thông ghi nhận vi phạm',
        captureDate: '2024-11-18T08:45:00Z',
        verified: true,
      },
    ],
    createdAt: '2024-11-18T09:00:00Z',
  },
  {
    id: '4',
    violationCode: 'VL004',
    violationNumber: 'BB2024004',
    violatorInfo: {
      name: 'Vũ Văn Giang',
      licenseNumber: '012345678907',
      idNumber: '001234567896',
      dateOfBirth: '1993-04-08',
      address: '147 Tôn Đức Thắng, Đống Đa, Hà Nội',
      phone: '0918273645',
    },
    vehicleInfo: {
      plateNumber: '29E-55555',
      type: 'Xe khách',
      brand: 'Hyundai',
      model: 'Universe',
      color: 'Trắng',
    },
    violationType: 'phone_while_driving',
    violationDate: '2024-11-22',
    violationTime: '16:20:00',
    location: {
      address: 'Đường Nguyễn Trãi',
      province: 'Hà Nội',
      district: 'Thanh Xuân',
      street: 'Nguyễn Trãi',
    },
    officer: {
      id: 'OFF004',
      name: 'Đinh Thị E',
      badgeNumber: 'CSGT004',
      unit: 'Đội CSGT số 3',
      rank: 'Trung úy',
    },
    description: 'Sử dụng điện thoại di động khi đang điều khiển xe',
    fine: 800000,
    pointsDeducted: 1,
    status: 'unpaid',
    evidence: [
      {
        id: 'EV007',
        type: 'photo',
        description: 'Ảnh chụp lái xe đang sử dụng điện thoại',
        captureDate: '2024-11-22T16:20:00Z',
        verified: true,
      },
    ],
    createdAt: '2024-11-22T16:30:00Z',
  },
  {
    id: '5',
    violationCode: 'VL005',
    violationNumber: 'BB2024005',
    violatorInfo: {
      name: 'Bùi Thị Hà',
      licenseNumber: '012345678908',
      idNumber: '001234567897',
      dateOfBirth: '1991-09-17',
      address: '258 Khâm Thiên, Đống Đa, Hà Nội',
      phone: '0967891234',
    },
    vehicleInfo: {
      plateNumber: '29F-66666',
      type: 'Xe máy',
      brand: 'Honda',
      model: 'SH',
      color: 'Xanh',
      owner: 'Bùi Thị Hà',
    },
    violationType: 'no_helmet',
    violationDate: '2024-11-25',
    violationTime: '07:30:00',
    location: {
      address: 'Đường Khâm Thiên',
      province: 'Hà Nội',
      district: 'Đống Đa',
      street: 'Khâm Thiên',
    },
    officer: {
      id: 'OFF005',
      name: 'Ngô Văn F',
      badgeNumber: 'CSGT005',
      unit: 'Đội CSGT số 1',
      rank: 'Thiếu úy',
    },
    description: 'Không đội mũ bảo hiểm khi điều khiển xe mô tô',
    fine: 400000,
    pointsDeducted: 0,
    status: 'paid',
    paymentInfo: {
      paymentId: 'PAY002',
      paymentMethod: 'cash',
      amount: 400000,
      paymentDate: '2024-11-25',
      receiptNumber: 'RCP002',
      status: 'completed',
    },
    evidence: [
      {
        id: 'EV008',
        type: 'photo',
        description: 'Ảnh vi phạm không đội mũ bảo hiểm',
        captureDate: '2024-11-25T07:30:00Z',
        verified: true,
      },
    ],
    createdAt: '2024-11-25T07:45:00Z',
  },
  {
    id: '6',
    violationCode: 'VL006',
    violationNumber: 'BB2024006',
    violatorInfo: {
      name: 'Trần Văn Khoa',
      licenseNumber: '012345678911',
      idNumber: '001234567900',
      address: '852 Xã Đàn, Đống Đa, Hà Nội',
      phone: '0945123789',
    },
    vehicleInfo: {
      plateNumber: '29G-77777',
      type: 'Xe tải',
      brand: 'Isuzu',
      color: 'Vàng',
    },
    violationType: 'overload_20_50',
    violationDate: '2024-11-24',
    violationTime: '13:00:00',
    location: {
      address: 'Trạm cân Pháp Vân',
      province: 'Hà Nội',
      district: 'Hoàng Mai',
    },
    officer: {
      id: 'OFF006',
      name: 'Lê Thị G',
      badgeNumber: 'CSGT006',
      unit: 'Trạm cân tải trọng',
      rank: 'Đại úy',
    },
    description: 'Chở hàng quá tải 35% so với quy định',
    fine: 12000000,
    pointsDeducted: 3,
    status: 'unpaid',
    evidence: [
      {
        id: 'EV009',
        type: 'document',
        description: 'Biên bản cân tải trọng',
        captureDate: '2024-11-24T13:00:00Z',
        verified: true,
      },
    ],
    notes: 'Yêu cầu dỡ bớt hàng trước khi tiếp tục di chuyển',
    createdAt: '2024-11-24T13:30:00Z',
  },
  // Thái Nguyên violations
  {
    id: '7',
    violationCode: 'VL007',
    violationNumber: 'BB2024007',
    violatorInfo: {
      name: 'Nguyễn Văn Tuấn',
      licenseNumber: '012345678911',
      idNumber: '011234567890',
      dateOfBirth: '1988-03-22',
      address: '45 Lương Ngọc Quyến, TP Thái Nguyên',
      phone: '0912111222',
      email: 'nguyenvantuan.tn@email.com',
    },
    vehicleInfo: {
      plateNumber: '20A-11111',
      type: 'Ô tô con',
      brand: 'Honda',
      model: 'Civic',
      color: 'Đen',
      owner: 'Nguyễn Văn Tuấn',
    },
    violationType: 'speed_limit_10_20',
    violationDate: '2024-11-10',
    violationTime: '15:45:00',
    location: {
      address: 'Đường Lương Ngọc Quyến',
      province: 'Thái Nguyên',
      district: 'TP Thái Nguyên',
      street: 'Lương Ngọc Quyến',
      landmark: 'Gần UBND tỉnh',
    },
    officer: {
      id: 'OFF007',
      name: 'Hoàng Văn Mạnh',
      badgeNumber: 'CSGT-TN001',
      unit: 'Phòng CSGT Thái Nguyên',
      rank: 'Trung úy',
    },
    description: 'Vượt quá tốc độ cho phép 15 km/h',
    fine: 1000000,
    pointsDeducted: 2,
    status: 'paid',
    paymentInfo: {
      paymentId: 'PAY003',
      paymentMethod: 'bank_transfer',
      amount: 1000000,
      paymentDate: '2024-11-12',
      transactionNumber: 'TXN789012',
      receiptNumber: 'RCP003',
      status: 'completed',
    },
    evidence: [
      {
        id: 'EV010',
        type: 'camera',
        description: 'Camera giao thông ghi nhận tốc độ 65 km/h (giới hạn 50 km/h)',
        captureDate: '2024-11-10T15:45:00Z',
        verified: true,
      },
    ],
    createdAt: '2024-11-10T16:00:00Z',
  },
  {
    id: '8',
    violationCode: 'VL008',
    violationNumber: 'BB2024008',
    violatorInfo: {
      name: 'Lê Văn Hùng',
      licenseNumber: '012345678913',
      idNumber: '011234567892',
      dateOfBirth: '1985-11-30',
      address: '67 Phan Đình Phùng, TP Thái Nguyên',
      phone: '0909333444',
    },
    vehicleInfo: {
      plateNumber: '20C-33333',
      type: 'Xe bán tải',
      brand: 'Ford',
      model: 'Ranger',
      color: 'Xanh',
      owner: 'Lê Văn Hùng',
    },
    violationType: 'wrong_lane',
    violationDate: '2024-11-18',
    violationTime: '09:20:00',
    location: {
      address: 'Đường Phan Đình Phùng',
      province: 'Thái Nguyên',
      district: 'TP Thái Nguyên',
      street: 'Phan Đình Phùng',
    },
    officer: {
      id: 'OFF008',
      name: 'Đỗ Thị Lan',
      badgeNumber: 'CSGT-TN002',
      unit: 'Đội CSGT số 1 - Thái Nguyên',
      rank: 'Thiếu úy',
    },
    description: 'Đi sai làn đường quy định',
    fine: 1200000,
    pointsDeducted: 1,
    status: 'unpaid',
    evidence: [
      {
        id: 'EV011',
        type: 'photo',
        description: 'Ảnh vi phạm đi sai làn',
        captureDate: '2024-11-18T09:20:00Z',
        verified: true,
      },
    ],
    createdAt: '2024-11-18T09:45:00Z',
  },
  {
    id: '9',
    violationCode: 'VL009',
    violationNumber: 'BB2024009',
    violatorInfo: {
      name: 'Phạm Thị Lan',
      licenseNumber: '012345678914',
      idNumber: '011234567893',
      dateOfBirth: '1990-09-05',
      address: '89 Quang Trung, TP Thái Nguyên',
      phone: '0976444555',
    },
    vehicleInfo: {
      plateNumber: '20D-44444',
      type: 'Xe máy',
      brand: 'Honda',
      model: 'Air Blade',
      color: 'Trắng',
      owner: 'Phạm Thị Lan',
    },
    violationType: 'no_registration',
    violationDate: '2024-11-22',
    violationTime: '11:10:00',
    location: {
      address: 'Đường Quang Trung',
      province: 'Thái Nguyên',
      district: 'TP Thái Nguyên',
      street: 'Quang Trung',
      landmark: 'Trước chợ Quang Trung',
    },
    officer: {
      id: 'OFF009',
      name: 'Vũ Văn Tuấn',
      badgeNumber: 'CSGT-TN003',
      unit: 'Đội CSGT số 2 - Thái Nguyên',
      rank: 'Trung úy',
    },
    description: 'Không có giấy đăng ký xe',
    fine: 800000,
    pointsDeducted: 0,
    status: 'unpaid',
    evidence: [
      {
        id: 'EV012',
        type: 'document',
        description: 'Biên bản kiểm tra không xuất trình được giấy đăng ký xe',
        captureDate: '2024-11-22T11:10:00Z',
        verified: true,
      },
    ],
    createdAt: '2024-11-22T11:30:00Z',
  },
];

export const getViolationById = (id: string): TrafficViolation | undefined => {
  return mockViolations.find((violation) => violation.id === id);
};

export const getViolationsByStatus = (status: string): TrafficViolation[] => {
  return mockViolations.filter((violation) => violation.status === status);
};

export const getViolationsByLicense = (licenseNumber: string): TrafficViolation[] => {
  return mockViolations.filter(
    (violation) => violation.violatorInfo.licenseNumber === licenseNumber,
  );
};

export const getViolationsByPlate = (plateNumber: string): TrafficViolation[] => {
  return mockViolations.filter(
    (violation) => violation.vehicleInfo?.plateNumber === plateNumber,
  );
};

export const calculateTotalFines = (violations: TrafficViolation[]): number => {
  return violations.reduce((total, violation) => total + violation.fine, 0);
};

export const calculateUnpaidFines = (violations: TrafficViolation[]): number => {
  return violations
    .filter((v) => v.status === 'unpaid' || v.status === 'pending')
    .reduce((total, violation) => total + violation.fine, 0);
};